### PR TITLE
Create Number_Guessing_Game.py

### PR DESCRIPTION
**Pull request by Aditi22Bansal**
How the Game Works:
Random Number Generation: The game generates a random number between 1 and 100 using the random.randint(1, 100) function.
User Input: The user is asked to guess the number.
Feedback:
If the guessed number is lower than the generated number, the program tells the user it's "Too low."
If the guessed number is higher, the program says "Too high."
Success: When the user guesses the correct number, the game congratulates the user and displays the number of attempts.
Error Handling: If the user enters invalid input (like text or special characters), it catches the error and prompts the user to enter a valid number.

### CODE REVIEW

**Comment by darkhorse404** [comment]
Please put your project file in a folder and upload the folder

**Comment by Aditi22Bansal** [comment]
@darkhorse404 
Done
Kindly check

**Comment by Aditi22Bansal** [comment]
@darkhorse404 
Kindly check and merge
Thankyou

**Comment by Aditi22Bansal** [comment]
@darkhorse404 
Please add hactoberfest label so that it shows on my account

**Pull request merged**
